# Spatial Filtering

**Spatial Filtering** technique is used directly on pixels of an image. Mask is usually considered to be added in size so that it has specific center pixel. This mask is moved on the image such that the center of the mask traverses all image pixels.

1. Linear Spatial Filter
2. Non-linear Spatial Filter

![Image filtering 1](dataset/imgs/spatial1.jpg)


**Smoothing Spatial Filter:** Smoothing filter is used for blurring and noise reduction in the image. Blurring is pre-processing steps for removal of small details and Noise Reduction is accomplished by blurring.

Types of Smoothing Spatial Filter:

1. Linear Filter (Mean Filter)
2. Order Statistics (Non-linear) filter 

These are explained as following below.

**Mean Filter:**

Linear spatial filter is simply the average of the pixels contained in the neighborhood of the filter mask. The idea is replacing the value of every pixel in an image by the average of the grey levels in the neighborhood define by the filter mask.

Types of Mean filter:

> *(i) Averaging filter:* It is used in reduction of the detail in image. All coefficients are equal.


![Averaging](dataset/imgs/spatial2.jpg)


> *(ii) Weighted averaging filter:* In this, pixels are multiplied by different coefficients. Center pixel is multiplied by a higher value than average filter.


**Order Statistics Filter:**

It is based on the ordering the pixels contained in the image area encompassed by the filter. It replaces the value of the center pixel with the value determined by the ranking result. Edges are better preserved in this filtering.

Types of Order statistics filter:

> *(i) Minimum filter:* 0th percentile filter is the minimum filter. The value of the center is replaced by the smallest value in the window.

> *(ii) Maximum filter:* 100th percentile filter is the maximum filter. The value of the center is replaced by the largest value in the window.

> *(iii) Median filter:* Each pixel in the image is considered. First neighboring pixels are sorted and original values of the pixel is replaced by the median of the list.

## Image Convolution

![image convolution gif](dataset/imgs/spatial3.jpg)


**How one performs convolution on an image?**

![Convolution of image](dataset/imgs/spatial4.jpg)

And how do the values are computed? Here is an example...

![Convolution of image, arithmetics](dataset/imgs/spatial5.gif)

What if the image is multi-channel?

So, the kernel would also be a multi-channel kernel, and the convolution will occur on all channels. This is how it is demostrated.

![multi-channel convolution](dataset/imgs/spatial8.jpg)

Now, look at how it moves in animation:

![Multi-channel convolution](dataset/imgs/spatial6.gif)


![image sharpening](dataset/imgs/spatial7.png)

## Convolution Operation

### scipy.signal.convolve2d()

In [5]:
from scipy import signal


# for example 
kernel = [
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
]

img = [
    [190, 206, 228, 238],
    [180, 205, 227, 219],
    [182, 203, 211, 159],
    [184, 212, 206, 177]
]

print(signal.convolve2d(img, kernel, boundary="symm"))


[[184 184 201 241 267 267]
 [184 184 201 241 267 267]
 [143 143 209 272 252 252]
 [161 161 205 260  29  29]
 [158 158 255 224 166 166]
 [158 158 255 224 166 166]]


In [6]:
from scipy import signal


gaussian_kernel = [
    [0.0116, 0.0861, 0.0116],
    [0.0861, 0.6366, 0.0861],
    [0.0116, 0.0861, 0.0116]
]

img_matrix = [
    [202, 195, 192, 191],
    [216, 211, 200, 209],
    [224, 212, 215, 227],
    [224, 205, 227, 230]
]


print(signal.convolve2d(img_matrix, gaussian_kernel, boundary="symm"))

[[208.3231 208.3231 202.413  198.5626 198.1941 198.1941]
 [208.3231 208.3231 202.413  198.5626 198.1941 198.1941]
 [220.6117 220.6117 214.8457 208.0947 213.8241 213.8241]
 [227.9516 227.9516 218.6319 221.3496 230.4079 230.4079]
 [228.1421 228.1421 215.5618 230.1563 235.5418 235.5418]
 [228.1421 228.1421 215.5618 230.1563 235.5418 235.5418]]


## Median Filter

In [56]:
from scipy.ndimage import median_filter

img = [
    [23, 51, 23, 32],
    [32, 44, 44, 23],
    [23, 23, 44, 32],
    [44, 44, 23, 23],
    [44, 44, 23, 23]
]


# Median Spatial Domain Filtering
median_filter(img, size=3, )

array([[32, 32, 32, 32],
       [23, 32, 32, 32],
       [32, 44, 32, 23],
       [44, 44, 23, 23],
       [44, 44, 23, 23]])

## Gaussian Filter

In [52]:
from scipy.ndimage import gaussian_filter


img_matrix = [
    [202, 195, 192, 191],
    [216, 211, 200, 209],
    [224, 212, 215, 227],
    [224, 205, 227, 230]
]

print(gaussian_filter(img_matrix, sigma=0.5))


# gaussian kernel for sigma = 0.5 is:
# gaussian_kernel = [
#     [0.0116, 0.0861, 0.0116],
#     [0.0861, 0.6366, 0.0861],
#     [0.0116, 0.0861, 0.0116]
# ]


[[202 196 192 192]
 [214 208 201 208]
 [221 212 214 223]
 [221 209 223 228]]


## Mean Filter

In [55]:
import numpy as np
  

def mean_filter(img, mask_size):

    row, col = len(img), len(img[0])

    # Develop Averaging filter mask
    mask = np.ones([mask_size, mask_size], dtype = int)
    mask = mask / 9

    # Convolve the mask over the image
    img_new = np.zeros([row, col])
    
    for i in range(1, row-1):
        for j in range(1, col-1):
            temp = img[i-1, j-1]*mask[0, 0]+img[i-1, j]*mask[0, 1]+img[i-1, j + 1]*mask[0, 2]+img[i, j-1]*mask[1, 0]+ img[i, j]*mask[1, 1]+img[i, j + 1]*mask[1, 2]+img[i + 1, j-1]*mask[2, 0]+img[i + 1, j]*mask[2, 1]+img[i + 1, j + 1]*mask[2, 2]
            img_new[i, j]= temp
            
    img_new = img_new.astype(np.uint8)
    return img_new


# for example
img = [
    [202, 195, 192, 191],
    [216, 211, 200, 209],
    [224, 212, 215, 227],
    [224, 205, 227, 230]
]
img = np.array(img)

print(mean_filter(img, 3))

[[  0   0   0   0]
 [  0 207 205   0]
 [  0 214 215   0]
 [  0   0   0   0]]
